module.exports.dogbreed = ['Affenpinscher',
    'Afghan Hound',
    'Airedale Terrier',
    'Alaskan Malamute',
    'American Staffordshire Bull Terrier',
    'Anatolian Shepherd Dog',
    'Australian Cattle Dog',
    'Australian Kelpie',
    'Australian Shepherd Dog',
    'Australian Silky Terrier',
    'Australian Terrier',
    'Basenji',
    'Basset Fauve de Bretagne',
    'Basset Hound',
    'Beagle',
    'Bearded Collie',
    'Bedlington Terrier',
    'Belgian Shepherd Dog',
    'Bernese Mountain Dog',
    'Bichon Frise',
    'Bloodhound',
    'Border Collie',
    'Border Terrier',
    'Borzoi',
    'Boston Terrier',
    'Bouvier des Flandres',
    'Boxer',
    'Bracco Italiano',
    'Briard',
    'Brittany',
    'Bull Terrier',
    'Bull Terrier Miniature',
    'Bulldog',
    'Bullmastiff',
    'Cairn Terrier',
    'Cavalier King Charles Spaniel',
    'Cesky Terrier',
    'Chesapeake Bay Retriever',
    'Chihuahua (Smooth Coat)',
    'Chinese Crested',
    'Chow Chow (Smooth)',
    'Clumber Spaniel',
    'Collie',
    'Curly-Coated Retriever',
    'Dachshund',
    'Dalmatian',
    'Dandie Dinmont Terrier',
    'Deerhound',
    'Dobermann',
    'Dogue de Bordeaux',
    'English Setter',
    'English Springer Spaniel',
    'English Toy Terrier (Black & Tan)',
    'Field Spaniel',
    'Finnish Lapphund',
    'Finnish Spitz',
    'Flat-Coated Retriever',
    'Others',
    'Mix'];

module.exports.catbreed = ['Abyssinian',
    'Australian Mist',
    'Balinese',
    'Bengal',
    'Birman',
    'Bombay',
    'British Shorthair',
    'Burmese',
    'Burmilla',
    'Cornish Rex',
    'Devon Rex',
    'Egyptian Mau',
    'Exotic Shorthair',
    'Japanese Bobtail',
    'Korat',
    'La Perms',
    'Maine Coon',
    'Manx',
    'Norwegian Forest',
    'Ocicat',
    'Oriental Shorthair',
    'Persian Longhair',
    'Ragdoll',
    'Russian Blue',
    'Scottish Fold',
    'Siamese',
    'Siberian Forest',
    'Singapura',
    'Snowshoe',
    'Somali',
    'Sphynx',
    'Tiffanie',
    'Tonkinese',
    'Turkish Van'];

    module.exports.shelterNames=['Canine Estates',
    'Canine Platoon',
    'Citizen Canine',
    'Clip-n-Dales Pets',
    'Creature Comforts',
    'Critters and Creatures',
    'Doggy Divine',
    'Dogmatic Care Center',
    'Dogs Trust',
    'Dogs without Borders',
    'Dumb Friends League',
    'Endless Pawsabilities',
    'Fences for Fido',
    'Friends for Life',
    'Friends of Animals',
    'Fur and Fluff',
    'Beyond the Border',
    'Maw and Paw',
    'Mucky Pups',
    'National Cat Protection Society',
    'New Beginnings',
    'North Shore Shelters',
    'Of the Chain',
    'Pampered Paws',
    'Patriot PAWS',
    'Pawing Packs',
    'Paws for Applause',
    'Pawsitive Attitude',
    'Perfect Touch Shelters',
    'Pet Paradise',
    'Pets for the Elderly',
    'Pick of the Litter',
    'Safe Heaven',
    'Eden for Pups',
    'Pooch Parlor',
    'Posh Paws',
    'Pretty Paws',
    'Pristine Pups',
    'Puppy Love',
    'Puppy Paws',
    'Pure Mutts',
    'Raise the Woof',
    'Red Rover',
    'Save a Pet'];